pipeline {
    agent any

    environment {
        IMAGE_NAME = "taskmanager-backend"
        CONTAINER_NAME = "taskmanager-backend-stable"
        PORT = "5001"
    }

    stages {
        stage('Pull Code') {
            steps {
                echo 'Pulling latest code...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing npm packages...'
                dir('TaskManager/backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Run Checks') {
            steps {
                echo 'Running syntax check...'
                dir('TaskManager/backend') {
                    bat 'node --check src/server.js'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                dir('TaskManager/backend') {
                    bat "docker build -t taskmanager-backend:%BUILD_NUMBER% ."
                }
            }
        }

        stage('Deploy Container') {
            steps {
                echo 'Deploying container...'
                bat 'docker stop taskmanager-backend & exit 0'
                bat 'docker rm taskmanager-backend & exit 0'
                bat 'docker stop taskmanager-backend-stable & exit 0'
                bat 'docker rm taskmanager-backend-stable & exit 0'
                bat 'docker network create taskmanager-network & exit 0'
                bat 'docker run -d --name taskmanager-backend-stable --network taskmanager-network -p 5001:5000 -e MONGO_URI=mongodb://taskmanager-mongodb:27017/taskmanager taskmanager-backend:%BUILD_NUMBER%'
            }
        }

        stage('Health Check') {
            steps {
                echo 'Waiting for app to start...'
                bat 'timeout /t 10 /nobreak'
                bat 'curl -f http://localhost:5001/health'
                echo 'Health check PASSED!'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
            bat 'docker stop taskmanager-backend-stable & exit 0'
        }
    }
}